version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Raise all npm pull requests with custom labels
    labels:
      - "npm dependencies"
    ignore:
      - match:
      # targets react & react dom
        dependency_name: "*experimental*"
      - match:
        dependency_name: "next"
        versions: ["10.0.6"]