import type { LocalizedSheetContent } from "@/types/content";

const legal: LocalizedSheetContent = {
	de: [
		{
			sectionTitle: "Angaben gemäß § 5 TMG",
			entries: [
				{
					content:
						"Manuel Fridolin Dugué\nGörlitzer Str. 23, 01099 Dresden\nKoordinaten: 51.066050 13.754475",
				},
				{
					title: "Kontakt",
					content:
						"Telefon: +49 151 58791155\nE-Mail: post@manueldugue.de",
				},
				{
					title: "Umsatzsteuer-ID",
					content:
						"Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: DE272030502",
				},
			],
		},
		{
			sectionTitle: "Urheberrecht",
			entries: [
				{
					content:
						"Texte, Bilder, Grafiken sowie Gestaltung und Layout dieser Seiten unterliegen weltweitem Urheberrecht. Die unerlaubte Verwendung, Reproduktion oder Weitergabe einzelner Inhalte oder kompletter Seiten wird sowohl straf- als auch zivilrechtlich verfolgt.",
				},
			],
		},
		{
			sectionTitle: "Google Analytics",
			entries: [
				{
					content:
						"Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. Google Analytics verwendet Cookies, die eine Analyse der Benutzung der Website ermöglichen. Die durch den Cookie erzeugten Informationen über die Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.\nDie IP-Anonymisierung ist auf dieser Website aktiviert. Die IP-Adresse der Nutzer wird innerhalb der Mitgliedstaaten der Europäischen Union gekürzt.\nSie können die Erfassung durch Google Analytics verhindern, indem Sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren.",
					links: [
						"https://tools.google.com/dlpage/gaoptout?hl=de",
					],
				},
			],
		},
		{
			sectionTitle: "Facebook-Plugins",
			entries: [
				{
					content:
						"Auf diesen Seiten sind Plugins des sozialen Netzwerks Facebook integriert. Wenn Sie eine Seite besuchen, die ein solches Plugin enthält, wird eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt. Facebook erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse diese Seite besucht haben.",
				},
			],
		},
	],
	en: [
		{
			sectionTitle: "Provider details (§ 5 TMG)",
			entries: [
				{
					content:
						"Manuel Fridolin Dugué\nGörlitzer Str. 23, 01099 Dresden, Germany\nCoordinates: 51.066050 13.754475",
				},
				{
					title: "Contact",
					content:
						"Phone: +49 151 58791155\nEmail: post@manueldugue.de",
				},
				{
					title: "VAT ID",
					content:
						"VAT identification number according to § 27 a of the German VAT Act: DE272030502",
				},
			],
		},
		{
			sectionTitle: "Copyright",
			entries: [
				{
					content:
						"Texts, images, graphics, as well as the design and layout of these pages are subject to worldwide copyright protection. Unauthorized use, reproduction or dissemination of individual contents or complete pages will be prosecuted under both criminal and civil law.",
				},
			],
		},
		{
			sectionTitle: "Google Analytics",
			entries: [
				{
					content:
						"This website uses Google Analytics, a web analytics service provided by Google Inc. Google Analytics uses cookies that enable analysis of website usage. The information generated by the cookie about your use of this website is usually transmitted to a Google server in the USA and stored there.\nIP anonymization is activated on this website. The IP address of users is truncated within member states of the European Union.\nYou can prevent data collection by Google Analytics by downloading and installing the browser plugin available at the following link.",
					links: [
						"https://tools.google.com/dlpage/gaoptout?hl=en",
					],
				},
			],
		},
		{
			sectionTitle: "Facebook plugins",
			entries: [
				{
					content:
						"Plugins of the social network Facebook are integrated on these pages. When you visit a page that contains such a plugin, a direct connection is established between your browser and the Facebook server. Facebook receives the information that you visited this page with your IP address.",
				},
			],
		},
	],
};

export default legal;
