name: Types & Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: check types
        run: bun tsc

      - name: linting
        run: bun lint
